### ISSUE TITLE
type 'List<InlineSpan>' is not a subtype of type 'List<TextSpan>'

### ISSUE THREAD

**Issue by rhymelph** [fluttercandies/extended_text#20]
extended_text版本：0.6.0
Flutter版本：1.7.8
重现步骤：列表中调用setState刷新
异常栈：
```html
I/flutter ( 4742): #0      OverFlowTextSpan.== (package:extended_text/src/over_flow_text_span.dart:35:41)
I/flutter ( 4742): #1      ExtendedRenderParagraph.overFlowTextSpan= (package:extended_text/src/extended_render_paragraph.dart:116:15)
I/flutter ( 4742): #2      ExtendedRichText.updateRenderObject (package:extended_text/src/extended_rich_text.dart:167:9)
I/flutter ( 4742): #3      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726:12)
I/flutter ( 4742): #4      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5206:11)
I/flutter ( 4742): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 4742): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 4742): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 4742): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 4742): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 4742): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #23     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 4742): #24     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 4742): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 4742): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 4742): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #46     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 4742): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 4742): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #52     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 4742): #53     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 4742): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #61     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 4742): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #65     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 4742): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 4742): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #73     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 4742): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #75     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
I/flutter ( 4742): #76     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1113:34)
I/flutter ( 4742): #77     Iterable.forEach (dart:core/iterable.dart:277:30)
I/flutter ( 4742): #78     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1139:24)
I/flutter ( 4742): #79     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1084:7)
I/flutter ( 4742): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #83     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 4742): #84     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 4742): #85     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 4742): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #91     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #93     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #97     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 4742): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #103    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 4742): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #105    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 4742): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #109    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 4742): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #113    StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 4742): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 4742): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 4742): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 4742): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 4742): #121    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter ( 4742): #122    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 4742): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 4742): #124    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 4742): #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 4742): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 4742): #127    _rootRun (dart:async/zone.dart:1124:13)
I/flutter ( 4742): #128    _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter ( 4742): #129    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
I/flutter ( 4742): #130    _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 4742): #131    _drawFrame (dart:ui/hooks.dart:194:3)
```

**Comment by kkyjh** [comment]
same error!!
so, i changed old version 
  extended_text: '0.5.8'
  extended_text_library: '0.4.1'

**Comment by zmtzawqlp** [comment]
please provide demo for this

**Comment by zmtzawqlp** [comment]
@rhymelph @kkyjh done
