### ISSUE TITLE
Text failed to display when switch between brightness

### ISSUE THREAD

**Issue by AlexVincent525** [fluttercandies/extended_text#48]
## Step to Reproduce

Place a `ExtendedText` with some content, then switch between brightness, the error will occurred.

<details><summary>Minimum code to reproduce</summary>
<p>

```Dart
import 'package:flutter/material.dart';
import 'package:extended_text/extended_text.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool darkMode = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        brightness: darkMode ? Brightness.dark : Brightness.light,
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ExtendedText("This is just a testing paragraph..."),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.brightness_4),
          onPressed: () {
            setState(() {
              darkMode = !darkMode;
            });
          },
        ),
      ),
    );
  }
}
```

</p>
</details>

## Logs

<details><summary>Error Log</summary>
<p>

```Dart
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 768 pos 12: '!_needsLayout': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ExtendedText file:///Users/alex/Documents/FlutterProjects/flutter_app/lib/main.dart:26:13
When the exception was thrown, this was the stack: 
#2      TextPainter._computeCaretMetrics (package:flutter/src/painting/text_painter.dart:768:12)
#3      TextPainter.getOffsetForCaret (package:flutter/src/painting/text_painter.dart:742:5)
#4      ExtendedRenderParagraph.getOffsetForCaret (package:extended_text/src/extended_render_paragraph.dart:514:25)
#5      ExtendedRenderParagraph._paintSpecialTextChildren (package:extended_text/src/extended_render_paragraph.dart:758:30)
#6      ExtendedRenderParagraph._paintSpecialText (package:extended_text/src/extended_render_paragraph.dart:750:5)
...
The following RenderObject was being processed when the exception was fired: ExtendedRenderParagraph#e6b66 relayoutBoundary=up2
...  parentData: offset=Offset(0.0, 399.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=Infinity)
...  semantics node: SemanticsNode#3
...    Rect.fromLTRB(0.0, 399.0, 179.0, 413.0)
...    label: "This is just a testing paragraph..."
...    textDirection: ltr
...  size: Size(179.0, 14.0)
...  textAlign: start
...  textDirection: ltr
...  softWrap: wrapping at box width
...  overflow: clip
...  textScaleFactor: 0.8
...  locale: en_US
...  maxLines: unlimited
  text: TextSpan
    debugLabel: lerp((englishLike body1 2014).merge(whiteCupertino body1) ⎯0.1→ (lerp(englishLike body1 2014 ⎯0.1→ englishLike body1 2014)).merge(lerp(whiteCupertino body1 ⎯0.1→ blackCupertino body1)))
    inherit: false
    color: Color(0xfefdfdfd)
    family: .SF UI Text
    size: 14.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "This is just a testing paragraph..."
RenderObject: ExtendedRenderParagraph#e6b66 relayoutBoundary=up2
  parentData: offset=Offset(0.0, 399.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=Infinity)
  semantics node: SemanticsNode#3
    Rect.fromLTRB(0.0, 399.0, 179.0, 413.0)
    label: "This is just a testing paragraph..."
    textDirection: ltr
  size: Size(179.0, 14.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  textScaleFactor: 0.8
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    debugLabel: lerp((englishLike body1 2014).merge(whiteCupertino body1) ⎯0.1→ (lerp(englishLike body1 2014 ⎯0.1→ englishLike body1 2014)).merge(lerp(whiteCupertino body1 ⎯0.1→ blackCupertino body1)))
    inherit: false
    color: Color(0xfefdfdfd)
    family: .SF UI Text
    size: 14.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "This is just a testing paragraph..."
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</p>
</details>

flutter doctor
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.7-pre.1, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
```

**Comment by AlexVincent525** [comment]
Seems fixed. 👍
