### ISSUE TITLE
selectionEnabled is not working on iOS, but working on Android

### ISSUE THREAD

**Issue by ControlAdad** [fluttercandies/extended_text#59]
Am I missing something or selectionEnabled is not working on iOS:

`ExtendedText("Hi tehere 1234 5  5525234 523 45 42 5 5 2   254 5",style:getTextStyle(),selectionEnabled: true,),`

Selecting text has no effect and sometimes throws this error:

> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
> The following NoSuchMethodError was thrown building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#65417](dirty, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#2396b]], state: _OverlayEntryState#9e58c):
> The getter 'cutButtonLabel' was called on null.
> Receiver: null
> Tried calling: cutButtonLabel
> 
> The relevant error-causing widget was: 
>   MaterialApp file:///Users/abd/Programming/gits/p1/lib/generals/general_widget.dart:54:12
> When the exception was thrown, this was the stack: 
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
> #1      ExtendedCupertinoTextSelectionControls.buildToolbar (package:extended_text_library/src/selection/cupertino_text_selection_controls.dart:387:44)
> #2      ExtendedTextSelectionOverlay._buildToolbar (package:extended_text_library/src/selection/extended_text_selection_overlay.dart:329:34)
> #3      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:169:25)
> #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)

**Comment by ControlAdad** [comment]
I found the problem, on iOS selection is activated by double, but on Android by long click!
